### ISSUE TITLE
Gamemode Bug

### ISSUE THREAD

**Issue by Da-Dog** [Squaregentleman/MCDR-plugins#3]
![image](https://user-images.githubusercontent.com/38967721/82624940-b3142e80-9b98-11ea-872a-432912e6ea99.png)

**Comment by Squaregentleman** [comment]
playerinfoapi的问题
reeeeeee

**Comment by Da-Dog** [comment]
修了一下，不过只支持MCDR了，没做MCD的 :) 
我开个PR
